### ISSUE TITLE
Windows File System

### ISSUE THREAD

**Issue by igormaraujo** [davestewart/nuxt-areas#4]
There is a problem when I run a project at windows OS.

![image](https://user-images.githubusercontent.com/28158542/141357950-97648495-93b7-4bb1-b28e-c3ad6b526aa8.png)

**Comment by davestewart** [comment]
Yeah - it's a f***ing disaster!

I'm actually just attempting to fix this now.

Hoping to have this done in the next couple of hours.

Hang tight :)

**Comment by davestewart** [comment]
OK. Have appeared to have got there.

Just need to tidy the code up and do some more testing.

**Comment by davestewart** [comment]
OK, I've released 0.7.4:

- https://www.npmjs.com/package/nuxt-areas

It's working for me in a VM and on an Azure server, so pretty sure it's there.

Can you try it and let me know if it works for you?

**Comment by ptako** [comment]
I've tried, error is gone, seems to be fine. Thanks!

**Comment by davestewart** [comment]
Brilliant. Thanks!

Closed by #5.
