### ISSUE TITLE
Property of method "$store" is not defined on the instance.

### ISSUE THREAD

**Issue by nickdawes** [davestewart/nuxt-areas#8]
# Issue
Cannot reference `this.$store` inside default layout `areas/app/layouts/default.vue`.

### Error
`Property or method "$store" is not defined on the instance but referenced during render.`

### Code example

    /areas/app/layouts/default.vue

    export default {
      ...
      head() {
        ...
        if (this.$store.state.property) {
        ...
        }
      }
    }

## .debug/nuxt.js output

    // Areas updated your Nuxt options as follows  
    export const nuxt = {  
      dir: {  
        assets: 'assets',  
        app: 'app',  
        layouts: 'areas/app/layouts',  
        middleware: 'middleware',  
        pages: 'areas/app/pages',  
        static: 'static',  
        store: 'areas/app/store',  
        components: 'areas/app/components'  
      },  
      alias: {
        '~~': 'C:\\web\\project',
        '@@': 'C:\\web\\project',
        '~': 'C:\\web\\project',
        '@': 'C:\\web\\project',
        assets: 'C:\\web\\project\\assets',
        static: 'C:\\web\\project\\static',
        components: 'C:/web/project/areas/app/components',
        layouts: 'C:/web/project/areas/app/layouts',
        pages: 'C:/web/project/areas/app/pages',
        store: 'C:/web/project/areas/app/store'
      },
      components: [
        {
          path: '~/areas/app/components',
          pattern: '**/*.{vue,js,ts,tsx}',
          pathPrefix: false
        }
      ]
    }

## Store dir structure

    +- src
        +- areas
            +- app
                +- store
                |   +- index.js
                |   +- ui.js
                |   +- nav.js

## Environment
- Nuxt v2.15.6
- Windows 11

**Comment by davestewart** [comment]
Hi Nick,

Just checking, is `store/` in `areas/app/store` or `areas/store` ?

Does `areas/.debug/areas.js` show the area as registered?

**Comment by davestewart** [comment]
Here's the store dumped in the demo's `areas/app/layouts/default.vue`:

![image](https://user-images.githubusercontent.com/132681/141451990-715d7cb4-73e9-47f6-9933-08c8d96cbfbc.png)

You should also be able to inspect the store in the Vue Devtools as usual.

**Comment by davestewart** [comment]
Hmm... just looked at your config dump again, you do appear to have it correct.

 Did you restart the server?

**Comment by nickdawes** [comment]
Hey @davestewart! Thanks for picking this up so quickly.

To clarify, my folder structure is `root -> areas -> app -> store`, where my store files are held. I updated my original comment to reflect this.

**Comment by davestewart** [comment]
That's weird. 

I just tried it in the `head()` from `areas/app/layouts/default.vue` and it's fine.

Can you access `$store` from any other page when using areas?

Can you access store from a

**Comment by nickdawes** [comment]
I've just double checked, and yes; the same error occurs after restarting dev server and also appears in a production build. Worth mentioning, I'm implementing `areas` into an existing project- I'll try a fresh nuxt app.

I'll also try access `$store` from elsewhere within my existing project and let you know the result.

**Comment by davestewart** [comment]
Also, that error message usually implies you've used a variable in a template but you've pasted code from the script.

```
Property or method "$store" is not defined on the instance but referenced during render.
```

Can you paste the whole file?

**Comment by davestewart** [comment]
Also, what happens if you move `/areas/app/store` back to `/store` ?

**Comment by nickdawes** [comment]
Ok, so I've spun up a fresh nuxt app and seem to be having the same issue. It may be my implementation, so let's go through what I've done.

`npm i --save-dev nuxt-areas`

## nuxt.config.js

    ...
      buildModules: [
        'nuxt-areas'
      ]
    ...
`

## folder structure

    src -> areas -> app -> store -> index.js

    index.js
    export const state = () => ({
      test: 'test'
    })

## src/areas/app/layouts/default.vue

    <template>
      <Nuxt/>
    </template>

    <script>
    export default {
      name: "default",
      head() {
        console.log(this.$store)
      }
    }
    </script>

## src/areas/.debug/nuxt.js
    // Areas updated your Nuxt options as follows
    export const nuxt = {
      dir: {
        assets: 'assets',
        app: 'app',
        layouts: 'areas/app/layouts',
        middleware: 'middleware',
        pages: 'areas/app/pages',
        static: 'static',
        store: 'areas/app/store',
        components: 'areas/app/components'
      },
      alias: {
        '~~': 'C:\\web\\test-app',
        '@@': 'C:\\web\\test-app',
        '~': 'C:\\web\\test-app',
        '@': 'C:\\web\\test-app',
        assets: 'C:\\web\\test-app\\assets',
        static: 'C:\\web\\test-app\\static',
        components: 'C:/web/test-app/areas/app/components',
        layouts: 'C:/web/test-app/areas/app/layouts',
        pages: 'C:/web/test-app/areas/app/pages',
        store: 'C:/web/test-app/areas/app/store'
      },
      components: [
        {
          path: '~/areas/app/components',
          pattern: '**/*.{vue,js,ts,tsx}',
          pathPrefix: false
        }
      ]
    }


The above results in `undefined` in the console.

**Comment by nickdawes** [comment]
> Also, what happens if you move `/areas/app/store` back to `/store` ?

I've just tried, and this results in `this.$store` appearing in the output of the console.

**Comment by nickdawes** [comment]
> Also, that error message usually implies you've used a variable in a template but you've pasted code from the script.
> 
> ```
> Property or method "$store" is not defined on the instance but referenced during render.
> ```
> 
> Can you paste the whole file?
> 
> > Worth mentioning, I'm implementing areas into an existing project
> 
> That's interesting. `$store` should still be loaded, even if in `areas/app`.
> 
> What's in your Vue Devtools?

"No Vuex store detected"

**Comment by nickdawes** [comment]
Here's a [repo](https://github.com/nickdawes/nuxt-areas-issue), if it's useful.

**Comment by nickdawes** [comment]
I've just downloaded the demo app, and `STORE INITIALISED` appears in the console log. I'll see if I can spot a problem with my implementation, using the demo app as a comparison.

**Comment by davestewart** [comment]
So you're saying if there's only `app` then things break?

This may be an issue, as `app` is "excluded" from Areas's "internal" areas, because routing and stores are handled by Nuxt.

Let me check and come back to you.

**Comment by davestewart** [comment]
OK, this is a great catch!

It turns out, if the store is set using `dir` – at least in a module – you need to set nuxt's `config.store` option to `true`.

I do this anyway, but only when there are stores to add, so if no stores to add, then it doesn't get set. I've overridden this now and it works.

I don't know why this is so. It feels like an oversight on Nuxt's behalf, but then, Nuxt is complicated.

The only place I have seen this noted is in a GitHub issue, not even the docs:

https://github.com/nuxt/nuxt.js/issues/4912#issuecomment-555552344

Anyway. Working now; update to 0.7.5 and it should work.

**Comment by nickdawes** [comment]
Just updated, tested, works perfectly.

Cheers @davestewart !

**Comment by davestewart** [comment]
Well, thank YOU!

It was great of you to help us get to the bottom of things, and supplying a repo was really useful.

Keep me posted whether Areas is useful for you, and I'm sure you'll let me know if you find any other bugs :)

Cheers!
